### ISSUE TITLE
proot: can we separate it out into a separate project

### ISSUE THREAD

**Issue by cyphar** [rootless-containers/runrootless#20]
I've been recommending people use the proot plugin that you've written, but it's a bit difficult for people to *just* use it because it's part of this project. Would you mind if we separated it into a separate project and then placed it inside https://github.com/rootless-containers?

As an aside, did you want to put this project in the `rootless-containers` organisation as well?

**Comment by AkihiroSuda** [comment]
SGTM

Also, it would be to consider promoting our patches to Proot upstream when proto gets matured.

**Comment by AkihiroSuda** [comment]
Do we want to just convert this repo for proot or create a new repo for proot?

**Comment by cyphar** [comment]
It depends which you think is better. I reckon having an all-in-one repo is pretty useful, but it would be nice to have a separate repo for `proot` -- so maybe making a new one is better? If you like I can move both `runrootless` and the new `proot` into the organisation.

**Comment by AkihiroSuda** [comment]
OK, I'll create a fork of https://github.com/proot-me/PRoot under the org.
Shall we create a  "master" branch for our fork? e.g. `rootless-containers-master`.

BTW, do we want to rename `user.rootlesscontainers` xattr to `user.rootless-containers`, or do we want to keep `user.rootlesscontainers`? (either is fine for me)

**Comment by cyphar** [comment]
We could just call the branch `rootless-containers` and make it the master branch. As for `user.rootlesscontainers` I think the current name is fine (and changing it would break stuff). I will change the organisation name to match.

**Comment by cyphar** [comment]
Whichever you prefer. The xattr name `user.rootlesscontainers` matches most other multi-word xattrs that I've seen, but usually in project names and branches you use `-` to separate different words. But we can just make everything `rootlesscontainers` if you like that more -- it doesn't make much of a difference at the end of the day.

**Comment by AkihiroSuda** [comment]
Pushed https://github.com/rootless-containers/PRoot/tree/rootlesscontainers , plz feel free to rename.

**Comment by AkihiroSuda** [comment]
Also moved this repo itself from AkihiroSuda/runrootless to rootless-containers/runrootless
